function [surfaceData,pitchData,tsrData]=readPerfSurface(CpCtCqFileName,rowRangeStr)

%% read surface data
surfaceData = readmatrix(CpCtCqFileName, ...
    'FileType', 'text',...
    'Range', rowRangeStr,...
    'Delimiter', ' ',...
    'ConsecutiveDelimitersRule', 'join',...
    'LeadingDelimitersRule', 'ignore'...
    );

% remove negative entries
surfaceData(surfaceData < 0) = 0;

%% read pitch data
if nargout>1

    pitchData = readmatrix(CpCtCqFileName, ...
        'FileType', 'text',...
        'Range', '5:5',...
        'Delimiter', ' ',...
        'ConsecutiveDelimitersRule', 'join',...
        'LeadingDelimitersRule', 'ignore'...
        );

end

%% read TSR data
if nargout>2

    tsrData = readmatrix(CpCtCqFileName, ...
        'FileType', 'text',...
        'Range', '7:7',...
        'Delimiter', ' ',...
        'ConsecutiveDelimitersRule', 'join',...
        'LeadingDelimitersRule', 'ignore'...
        );
    
    % remove any NaN's it read in
    tsrData = tsrData(~isnan(tsrData));

end


